import Head from "next/head"
import Link from "next/link"
import styles from "./MainLayout.module.css"
import Navbar from "../Navbar"
type Props = {
  children: React.ReactNode
}

const MainLayout = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </>
  )
}

export default MainLayout
